### ISSUE TITLE
Добавить на главную ссылки на основные разделы каталога

### ISSUE THREAD

**Issue by stnlss** [stnlss/stnlss#1]
Добавить на главную ссылки на основные разделы каталога.

Необходимо добавить плашки ведущие на разделы каталога:

- Моторные масла
- Шины
- Аккумуляторы
- Ароматизаторы
- Автосвет

При клике на плашку переход в соответсвующий раздел каталога.

Размещаем ниже под сторис.

Референс:

![Image](https://github.com/user-attachments/assets/19cd6523-ddbd-4abd-86aa-8c9293f44410)

**Comment by makovpv** [comment]
>Необходимо добавить плашки ведущие на разделы каталога:
>
>...
>Шины
>...

именно в "Шины" или в "Легковые шины"?

**Comment by stnlss** [comment]
Пока просто шины
