### ISSUE TITLE
Не верное отображение сроков от эмекс Дубай

### ISSUE THREAD

**Issue by KSzild24** [stnlss/stnlss#13]
Часто отображается срок поставки 4 дня. Например ПН 992898014

![Image](https://github.com/user-attachments/assets/300401a9-9a3d-4411-83ab-021e18548f25)

В формуле таких значений нет.

![Image](https://github.com/user-attachments/assets/7de23b74-6550-4784-b108-19cc46cd3195)

**Comment by KSzild24** [comment]
1615627580

![Image](https://github.com/user-attachments/assets/e8f3e566-3240-4fcd-afa6-c3091bcd9c56)

**Comment by makovpv** [comment]
для данного PN ошибка сейчас не воспроизводится, 
но есть предположение о некорректном заполнении справочника Сроки Поставки в фин модели (нижняя граница диапазона не включает значение указанное в справочнике)

**Comment by KSzild24** [comment]
после исправления диапазонов сроков доставки проблема исчезла. Изначально не верно заполнил.
