### ISSUE TITLE
Есть в наличии в ззап, но на зилд не отображается

### ISSUE THREAD

**Issue by KSzild24** [stnlss/stnlss#15]
2320027010 на зилд отображается от ззап 2-3 дня и 13  тр. 
на ззап такого варианта нет. но есть в наличии. но за 33. 

![Image](https://github.com/user-attachments/assets/3300757a-1f19-485c-bd07-21f6c2e2527a)

![Image](https://github.com/user-attachments/assets/39a014ad-cfe3-47bb-9459-8ac7baac56ae)

**Comment by makovpv** [comment]
не удалось воспроизвести

**Comment by KSzild24** [comment]
STC0019 есть в наличии , но не отображается на зилд
![Image](https://github.com/user-attachments/assets/d55939f3-acb3-493a-a142-5cc5e61e9f4a)

![Image](https://github.com/user-attachments/assets/129f6297-41f5-4335-a7a4-a9b869f43b90)

**Comment by KSzild24** [comment]
FJ15017HRWHX 

![Image](https://github.com/user-attachments/assets/98e2f702-1503-41cf-86e6-29121f1e873d)

![Image](https://github.com/user-attachments/assets/026eeb8c-7a52-48b6-ac1b-a044292c0c26)

**Comment by stnlss** [comment]
Что с этой задачей?

**Comment by KSzild24** [comment]
81A827506 та же ситуация

![Image](https://github.com/user-attachments/assets/bf10c5b3-d920-49da-8a96-206e85cb2459)


![Image](https://github.com/user-attachments/assets/4bbac68a-e397-4161-ab2e-fe0380ca4b64)

**Comment by makovpv** [comment]
если при запросе к API ZZap указать производителя (в данном случае это VAG), то api возвращает информацию
сейчас мы не указываем производителя при поиске
надо его как-то определять наверное
