### ISSUE TITLE
Параметр "Товарная группа" в финансовой модели

### ISSUE THREAD

**Issue by stnlss** [stnlss/stnlss#17]
Добавить в финансовую модель параметр "Товарная группа", для того чтобы настраивать ценообразование более точно. То есть коэффициенты могут задаваться просто для поставщика или для поставщика и выбранной категории товаров

**Comment by makovpv** [comment]
usercase:
1. пользователь выполняет поиск по PN
2. мы не знаем к какому разделу каталога относятся товары в результатах поиска
3. из-за этого мы не понимаем какой коэф-нт применять при наценке

наверное мы можем для каждого PN в результатах,  поискать соответствие в нашем каталоге и в итоге определить раздел.
но, 
1. мы можем не найти соответствие
2. мы можем найти соответствие в нескольких различных разделах (и тогда непонятно какой коэф-нт применять при наценке)

**Comment by stnlss** [comment]
Если не установлена товарная группа, но установлен поставщик с которым у нас АПИ, применяется наценка по поставщику. То есть надо добавить еще параметр на постащика наценка по дефолту.
