### ISSUE TITLE
Воркеры для проценки

### ISSUE THREAD

**Issue by stnlss** [stnlss/stnlss#18]
Воркеры для проценки по товарам по которым раннее уже была получена цена, но с момента последней проценки прошло более X дней.

**Comment by makovpv** [comment]
думаю не должна быть зависимость от того была ранее получена цена или нет

**Comment by stnlss** [comment]
согласен, но учитывая лимиты на проценку в некоторых АПИ, думал что должна быть очередность и приоритезация. То есть в первую очередь процениваем товары по которым раннее была получена цена (так как даный товар скорее всего есть у поставщика и мы в холостую не израсходуем запрос), далее товары которые мы еще ни разу не проценивали у этого поставщика и только потом товары которые мы раннее уже проценивали, но по ним ничего не вернулось (товара не было в наличии)
