### ISSUE TITLE
Установить счетчик Яндекс Метрики и разметить события

### ISSUE THREAD

**Issue by stnlss** [stnlss/stnlss#23]
Чтобы собирать аналитику по перформанс кампании надо поставить счетчик Яндекс метрики и на ключевые события повесить метки

**Comment by makovpv** [comment]
нужен список ключевых событий

**Comment by stnlss** [comment]
вход на сайт, переход на раздел каталога, клик на карточке товара, клик на кнопке фильтра, клик на кнопке добавить в корзину, клик на кнопке оформить, клик на кнопке поиска
