### ISSUE TITLE
Доработка функционала сторис

### ISSUE THREAD

**Issue by stnlss** [stnlss/stnlss#25]
1. Убрать визуальное отображение горизонтального скролла у сторис:

![Image](https://github.com/user-attachments/assets/90885b4b-437b-40f2-87de-27342f43ed6c)

2. Добавить красный кружок (обводку вокруг каждой сторис) если она не была просмотрена. Если она была просмотрена, то убирать красную обводку и помещать ее в конец списка

3. Возможно уменьшить размер шрифта, или сделать шире зону его написания (надо сделать так, чтобы текст помещался в две строки). Если не получится напиши максимальное количество символов, которую могут быть, чтобы текст умещался в две строки

4. В сторис сделать все кнопки и картинки со скругленными краями

![Image](https://github.com/user-attachments/assets/8c640d7b-e35e-404e-99cb-e82028c62fc1)

**Comment by makovpv** [comment]
>В сторис сделать все кнопки и картинки со скругленными краями

У нас кнопки со скругленными краями. 

Что надо изменить? 
Сделать более скругленными при таком же размере кнопки? 
Увеличить размер кнопки чтобы скругление стало более заметным?
