### ISSUE TITLE
Доработка фильтров для мобильной версии

### ISSUE THREAD

**Issue by stnlss** [stnlss/stnlss#28]
1. Открывать фильтры как отдельное окно  
2. Возможность указывать нижнюю и верхнюю границу по цене, задав ее в окошечках. Бегунок не обязательно.

![Image](https://github.com/user-attachments/assets/e53dac72-ced8-4a8f-8257-92cf43c20955)

3. Увеличить отступ после кнопки "Показать еще"

![Image](https://github.com/user-attachments/assets/d9846665-02b5-4e07-9edb-e09ebbbb75ff)

4. Кнопку показать "Показать еще" переименовать в "Показать все". При клике на кнопку открывать все варианты в новом окне

5. Кнопку "Показать товары" продублировать внизу окна фильтров

**Comment by makovpv** [comment]
> Открывать фильтры как отдельное окно

давай чуть подробнее. Речь про десктоп или про мобильный?

**Comment by makovpv** [comment]
> Кнопку "Показать товары" продублировать внизу окна фильтров

она и так уже продублирована

**Comment by stnlss** [comment]
речь про мобильную версию

**Comment by makovpv** [comment]
![Image](https://github.com/user-attachments/assets/2574fa96-7a62-4e39-a925-e1b198f416c5)

**Comment by makovpv** [comment]
![Image](https://github.com/user-attachments/assets/097fb6cd-98ad-4819-8431-609306699ce7)

**Comment by makovpv** [comment]
- _то есть они открываются как отдельное окошко_
- _окно на весь экран которое можно закрыть_
- _и при переходе на раздел фильтра - также открывается новое окно_
- _авито в раздел моторные масла_
- _в фильтрах можно кнопку показать товары - также закрепить внизу экрана по центру_
