### ISSUE TITLE
Кнопка в корзину на карточке с лучшими предложениями

### ISSUE THREAD

**Issue by KSzild24** [stnlss/stnlss#40]
Заменить в карточке товара значок корзина на фразу "Добавит в корзину"

**Comment by makovpv** [comment]
уточним что такое "карточка товара"

ты имеешь ввиду эти прямоугольники в разделе каталога?
там просто не очень много места

или ты имеешь ввиду отдельную страницу с описанием товара?
уточни пожалуйста, где ты хочешь поменять

**Comment by makovpv** [comment]
это вообще про карточку товара в каталоге или про карточки "Лучшая цена", "Экспресс доставка" и т.п.?

**Comment by KSzild24** [comment]
Это точно выдаются как лучшая цена или самая быстрая доставка. Там иконка картины, а нужно что бы текстом было написано "добавить в корзину"

**Comment by stnlss** [comment]
На карточке товара сейчас пиктограмма. Есть опасение, что не все пользователи смогут ее прочитать. На начальном этапе предлагаю сделать кнопку "в корзину" - написав это текстом

**Comment by makovpv** [comment]
я пытаюсь уточнить что такое "карточка товара".
насколько я понял - речь про зеленые прямоугольники "Лучшая цена", "Экспресс доставка" и т.п.
