### ISSUE TITLE
Изменить местоположение кнопки "перейти к оформлению" в разделе корзина

### ISSUE THREAD

**Issue by KSzild24** [stnlss/stnlss#41]
Перенести кнопку "перейти к оформлению" вниз после списка товаров

<img width="1363" alt="image" src="https://github.com/user-attachments/assets/e59cdfcf-fbb0-4af8-af93-52165b5ccdb2">

**Comment by makovpv** [comment]
уточни что такое "наполнение корзины"

**Comment by KSzild24** [comment]
Купленные позиции. 
Те
Капот
Аккумулятор 
Масло моторное

**Comment by makovpv** [comment]
т.е. надо кнопку "перейти к оформлению" переместить вниз?
под список купленных позиций, так?

**Comment by makovpv** [comment]
может лучше продублировать эту кнопку и сверху и снизу?
какой цели хотим добиться?

**Comment by makovpv** [comment]
перенес вместе с итоговой информацией _"N позиций на Х руб"_, если нет возражений
