### ISSUE TITLE
Бизнес логика поиска по номеру

### ISSUE THREAD

**Issue by KSzild24** [stnlss/stnlss#45]
сейчас при вводе ПН клиентом мы одновременно делаем запросы всем поставщикам. 
предлагаю сделать это в 3 этапа . 
1 - запрос в ззап. 
если наличия нет, то.
2 - этап, запрос ко всем поставщикам РФ, если наличия нет, то
3- этап запрос ко всем поставщикам ОАЭ

в итоге выдаем только наличие, при его отсутствии  показываем самый быстрый вариант из РФ, если и его нет до 10 дней , то самый быстрый вариант из ОАЭ

**Comment by makovpv** [comment]
поочередное выполнение запросов может увеличить общее время поиска (в три раза)

можно выполнять сразу все запросы как сейчас и есть, но затем результаты дополнительно фильтровать как ты предложил

**Comment by stnlss** [comment]
Согласен с твоим комментарием

**Comment by makovpv** [comment]
Проверьте бизнес логику, такие результаты будут, если применим новые правила поиска ПН по поставщикам.
Все ок?


| № | Поставщик | Срок поставки, дней | Цена, руб |
|--------|--------|--------|--------|
| 1 | Автопитер | 0 | 100 |
| 2 | Ззап | 0 | 900 |

результат: строка №2 (Ззап за 900 руб)


| № | Поставщик | Срок поставки, дней | Цена, руб |
|--------|--------|--------|--------|
| 1 | Автопитер | 8 | 500 |
| 2 | Ззап | 9 | 90 |
| 3 | Emex | 8 |200 |
| 4 | Emex | 12 |150 |

результат: строка №1 (Автопитер за 500 руб)


| № | Поставщик | Срок поставки, дней | Цена, руб |
|--------|--------|--------|--------|
| 1 | Автопитер | 11 | 70 |
| 2 | Ззап | 11 | 90 |
| 3 | Emex | 20 |200 |
| 4 | Emex | 22 |150 |

результат: строка №3 (Emex за 200 руб)
