### ISSUE TITLE
Ссылки в сторис на каталог с примененными фильтрами

### ISSUE THREAD

**Issue by stnlss** [stnlss/stnlss#5]
Необходимо доработать функциональность сторис в части ссылок для перехода на разделы сайта.

Предполагается, что при создании / редактировании сторис можно будет добавить ссылку, которая будет вести на конкретный раздел каталога с уже примененными фильтрами

**Comment by makovpv** [comment]
примеры ссылок с примененными фильтрами

шины по брендам
https://zild.ru/internal-catalog/69?brand=Cordiant&brand=Continental

шины по мин и макс цене
https://zild.ru/internal-catalog/69?priceMax=10000&priceMin=5000

ароматизаторы "Апельсин, лимон, ваниль"
https://zild.ru/internal-catalog/49?pvid=9v522&pvid=9v582&pvid=9v583&pvid=9v629&pvid=9v641&pvid=9v644&pvid=9v661

+комбинации

**Comment by makovpv** [comment]
редактировать сегменты сторис пока через БД

**Comment by stnlss** [comment]
да, ок делаю скриптами
